services:
    GhostRider.WGStats.listener:
        class: GhostRider\WGStats\event\main_listener
        arguments:
            - '@user'
            - '@config'
            - '@template'
        tags:
            - { name: event.listener }